### ISSUE TITLE
trying to run it on macos - major versio 61 error

### ISSUE THREAD

**Issue by lupitatg16** [picodotdev/blog-ejemplos#5]
Hi I followed the instructions... and I am getting this error:

> startup failed:
  General error during semantic analysis: Unsupported class file major version 61

while running ./gradlew run

any idea? thx

**Comment by davidgonzalez-sh** [comment]
What example are you trying to run from all repository examples?

**Comment by picodotdev** [comment]
What example are you trying to run from all repository examples?

**Comment by lupitatg16** [comment]
let me try to test it with earlier version then... thanks

**Comment by lupitatg16** [comment]
I have installed java 11 and run but still can't see the page, what is the url to open  
<img width="1110" alt="imagen" src="https://user-images.githubusercontent.com/95011791/155387087-7d2ab16e-719b-438f-88c3-af56badd5466.png">

**Comment by picodotdev** [comment]
http://localhost:8080/
